// AQI Scale Definitions and Health Information
export const AQI_SCALE_INFO = {
  CPCB: {
    name: 'CPCB (India)',
    description: 'Central Pollution Control Board standard for India',
    levels: [
      {
        range: [0, 50],
        label: 'Good',
        color: '#00ff88',
        bgColor: 'rgba(0, 255, 136, 0.1)',
        health: 'No adverse health effects expected. Air quality is satisfactory.',
        sensitiveGroups: 'General public - No restrictions',
        recommendations: ['Outdoor activities are safe', 'No need for air purifiers'],
      },
      {
        range: [51, 100],
        label: 'Satisfactory',
        color: '#a8ff3e',
        bgColor: 'rgba(168, 255, 62, 0.1)',
        health: 'Minor breathing discomfort may occur for people with respiratory conditions.',
        sensitiveGroups: 'People with asthma or heart conditions should limit strenuous activities',
        recommendations: ['Safe for most outdoor activities', 'Sensitive groups should avoid prolonged outdoor activities'],
      },
      {
        range: [101, 200],
        label: 'Moderately Polluted',
        color: '#ffb800',
        bgColor: 'rgba(255, 184, 0, 0.1)',
        health: 'Breathing discomfort in people with respiratory or heart disease.',
        sensitiveGroups: 'Children, elderly, and people with respiratory or heart disease are at higher risk',
        recommendations: [
          'Wear N95 masks for outdoor activities',
          'Reduce prolonged outdoor activities',
          'Keep air purifiers on',
          'Increase water intake',
        ],
      },
      {
        range: [201, 300],
        label: 'Poor',
        color: '#ff6b00',
        bgColor: 'rgba(255, 107, 0, 0.1)',
        health: 'Respiratory illnesses may increase. Common people may start experiencing breathing difficulties.',
        sensitiveGroups: 'Children, elderly, and people with respiratory or heart disease should avoid outdoor activities',
        recommendations: [
          'Wear N95/N99 masks when going outside',
          'Avoid outdoor activities',
          'Keep doors and windows closed',
          'Use air purifiers indoors',
          'Consult doctor if experiencing symptoms',
        ],
      },
      {
        range: [301, 400],
        label: 'Very Poor',
        color: '#cc00ff',
        bgColor: 'rgba(204, 0, 255, 0.1)',
        health: 'Respiratory illnesses significantly increase. General public affects. Sensitive people may face severe conditions.',
        sensitiveGroups: 'Everyone, especially children, elderly, and people with respiratory or heart disease must avoid outdoor activities',
        recommendations: [
          'Avoid all outdoor activities',
          'Wear N99 masks if going outside',
          'Keep indoors with air purifiers running',
          'Consult doctor immediately if experiencing severe symptoms',
          'Consider temporary relocation if possible',
        ],
      },
      {
        range: [401, 500],
        label: 'Severe',
        color: '#cc0000',
        bgColor: 'rgba(204, 0, 0, 0.1)',
        health: 'Respiratory illnesses significantly increase. General health may be affected.',
        sensitiveGroups: 'Everyone must avoid outdoor activities. Emergency medical care may be required.',
        recommendations: [
          'Stay indoors. Do not go outside.',
          'Keep air purifier running 24/7',
          'Wear N99/P100 masks if absolutely necessary to go outside',
          'Seek immediate medical attention if experiencing difficulty in breathing',
          'Close all windows and doors',
          'Consider evacuation if conditions persist',
        ],
      },
    ],
  },
  US_EPA: {
    name: 'US EPA AQI',
    description: 'Environmental Protection Agency standard (used for reference)',
    levels: [
      {
        range: [0, 50],
        label: 'Good',
        color: '#00ff88',
        bgColor: 'rgba(0, 255, 136, 0.1)',
        health: 'No health impacts.',
        sensitiveGroups: 'None',
        recommendations: ['Enjoy outdoor activities'],
      },
      {
        range: [51, 100],
        label: 'Moderate',
        color: '#a8ff3e',
        bgColor: 'rgba(168, 255, 62, 0.1)',
        health: 'Acceptable air quality. However, there may be risk for some people.',
        sensitiveGroups: 'Sensitive groups (children, elderly, people with respiratory/heart disease)',
        recommendations: ['Consider reducing prolonged outdoor exertion'],
      },
      {
        range: [101, 150],
        label: 'Unhealthy for Sensitive Groups',
        color: '#ffb800',
        bgColor: 'rgba(255, 184, 0, 0.1)',
        health: 'Members of sensitive groups may experience health effects.',
        sensitiveGroups: 'Sensitive groups at risk',
        recommendations: ['Reduce outdoor activities', 'Wear protective masks'],
      },
      {
        range: [151, 200],
        label: 'Unhealthy',
        color: '#ff6b00',
        bgColor: 'rgba(255, 107, 0, 0.1)',
        health: 'Some members of the general public may experience health effects.',
        sensitiveGroups: 'Everyone, especially sensitive groups affected',
        recommendations: ['Avoid outdoor activities', 'Use air purifiers'],
      },
      {
        range: [201, 300],
        label: 'Very Unhealthy',
        color: '#cc00ff',
        bgColor: 'rgba(204, 0, 255, 0.1)',
        health: 'Health alert. The entire general population is more likely to be affected.',
        sensitiveGroups: 'Everyone affected',
        recommendations: ['Remain indoors', 'Keep air purifiers running'],
      },
      {
        range: [301, 500],
        label: 'Hazardous',
        color: '#cc0000',
        bgColor: 'rgba(204, 0, 0, 0.1)',
        health: 'Health warning of emergency conditions. The entire population is more likely to be affected.',
        sensitiveGroups: 'Everyone at severe risk',
        recommendations: ['Stay indoors', 'Emergency measures needed'],
      },
    ],
  },
};

export const POLLUTANT_INFO = {
  PM25: {
    name: 'PM2.5 (Fine Particulates)',
    fullName: 'Particulate Matter less than 2.5 micrometers',
    unit: 'µg/m³',
    description:
      'Fine particles suspended in air that can penetrate deep into lungs and bloodstream. Major health hazard.',
    sources: [
      'Vehicle exhaust',
      'Industrial emissions',
      'Coal power plants',
      'Construction dust',
      'Biomass burning',
      'Cooking activities',
      'Natural sources (dust, pollen)',
    ],
    healthEffects: [
      'Respiratory diseases',
      'Cardiovascular issues',
      'Premature death in people with cardiopulmonary disease',
      'Asthma exacerbation',
      'Decreased lung function',
      'Chronic bronchitis',
    ],
    safeLevel: 'WHO recommends 15 µg/m³ (24-hour mean)',
    standardLevel: 'India CPCB: 60 µg/m³ (24-hour mean)',
  },
  PM10: {
    name: 'PM10 (Coarse Particulates)',
    fullName: 'Particulate Matter less than 10 micrometers',
    unit: 'µg/m³',
    description: 'Larger particles that can lodge in airways. Less harmful than PM2.5 but still significant.',
    sources: [
      'Road dust',
      'Construction sites',
      'Industrial processes',
      'Vehicle exhaust',
      'Crustal matter',
      'Pollen',
    ],
    healthEffects: [
      'Respiratory tract irritation',
      'Asthma',
      'Decreased lung function',
      'Bronchitis',
      'Coughing and shortness of breath',
    ],
    safeLevel: 'WHO recommends 45 µg/m³ (24-hour mean)',
    standardLevel: 'India CPCB: 100 µg/m³ (24-hour mean)',
  },
  NO2: {
    name: 'NO₂ (Nitrogen Dioxide)',
    fullName: 'Nitrogen Dioxide',
    unit: 'µg/m³',
    description: 'Reddish-brown toxic gas produced mainly from vehicle and industrial emissions.',
    sources: ['Vehicle exhaust', 'Power plants', 'Industrial facilities', 'Combustion processes'],
    healthEffects: [
      'Airway inflammation',
      'Reduced immune defense in lungs',
      'Increased susceptibility to respiratory infections',
      'Asthma exacerbation',
      'Decreased lung function',
    ],
    safeLevel: 'WHO recommends 25 µg/m³ (annual mean)',
    standardLevel: 'India CPCB: 80 µg/m³ (24-hour mean)',
  },
  SO2: {
    name: 'SO₂ (Sulfur Dioxide)',
    fullName: 'Sulfur Dioxide',
    unit: 'µg/m³',
    description: 'Colorless toxic gas with pungent smell produced from coal burning and industrial processes.',
    sources: ['Coal power plants', 'Oil refineries', 'Industrial smelters', 'Metal processing'],
    healthEffects: [
      'Respiratory tract irritation',
      'Bronchoconstriction',
      'Aggravation of asthma',
      'Cardiovascular effects',
      'Visibility reduction',
    ],
    safeLevel: 'WHO recommends 40 µg/m³ (24-hour mean)',
    standardLevel: 'India CPCB: 80 µg/m³ (24-hour mean)',
  },
  CO: {
    name: 'CO (Carbon Monoxide)',
    fullName: 'Carbon Monoxide',
    unit: 'mg/m³',
    description: 'Colorless, odorless toxic gas that reduces oxygen-carrying capacity of blood.',
    sources: ['Vehicle exhaust', 'Industrial emissions', 'Gas appliances', 'Fires'],
    healthEffects: [
      'Reduces oxygen supply to heart',
      'Cardiovascular stress',
      'Headaches and dizziness',
      'Impaired concentration',
      'Fatigue',
      'Can be fatal at high levels',
    ],
    safeLevel: 'WHO recommends no guideline for CO',
    standardLevel: 'India CPCB: 2 mg/m³ (8-hour mean)',
  },
  O3: {
    name: 'O₃ (Ozone)',
    fullName: 'Ground-level Ozone',
    unit: 'µg/m³',
    description: 'Colorless toxic gas formed from reaction of NOx and VOCs in sunlight. Secondary pollutant.',
    sources: [
      'Formed from reaction of NOx and VOCs (secondary)',
      'Vehicle exhaust',
      'Industrial emissions',
      'Photochemical reactions',
    ],
    healthEffects: [
      'Respiratory tract damage',
      'Reduced lung function',
      'Asthma exacerbation',
      'Increased susceptibility to infections',
      'Chronic obstructive pulmonary disease',
    ],
    safeLevel: 'WHO recommends 60 µg/m³ (maximum 8-hour daily mean)',
    standardLevel: 'India CPCB: 100 µg/m³ (8-hour mean)',
  },
  NH3: {
    name: 'NH₃ (Ammonia)',
    fullName: 'Ammonia',
    unit: 'µg/m³',
    description: 'Pungent colorless gas produced from industrial processes and agricultural activities.',
    sources: [
      'Animal husbandry',
      'Fertilizer production',
      'Wastewater treatment',
      'Industrial processes',
      'Vehicle emissions',
    ],
    healthEffects: [
      'Respiratory tract irritation',
      'Eye irritation',
      'Reduced lung function',
      'Airway inflammation',
      'Breathing difficulties',
    ],
    safeLevel: 'WHO recommends no specific guideline',
    standardLevel: 'India CPCB: 400 µg/m³ (24-hour mean)',
  },
};

export const HEALTH_ADVISORY_BY_AQI = {
  GOOD: {
    aqiRange: '0-50',
    generalPopulation: 'No health effects expected. Enjoy outdoor activities freely.',
    children: 'Safe to play outdoors. Normal physical activities recommended.',
    elderly: 'No restrictions. Normal activities safe.',
    respiratoryDisease: 'No need for precautions. Enjoy outdoor activities.',
    cardiovascularDisease: 'No restrictions. Safe outdoor activities.',
    suggestions: [
      'Perfect time for outdoor exercise and activities',
      'Open windows for natural ventilation',
      'No air purifiers needed',
    ],
  },
  SATISFACTORY: {
    aqiRange: '51-100',
    generalPopulation: 'Acceptable air quality. Safe for outdoor activities.',
    children: 'Can play outdoors but avoid strenuous activities if AQI > 80.',
    elderly: 'Safe for light outdoor activities.',
    respiratoryDisease: 'No major concerns but monitor if symptoms appear.',
    cardiovascularDisease: 'Safe. No specific precautions needed.',
    suggestions: [
      'Generally safe for outdoor activities',
      'Monitor air quality trends',
      'Use air purifier if AQI approaching 100',
    ],
  },
  MODERATELY_POLLUTED: {
    aqiRange: '101-200',
    generalPopulation: 'Consider reducing prolonged outdoor exertion.',
    children: 'Avoid outdoor play. Keep indoors if possible.',
    elderly: 'Avoid outdoor activities. Stay indoors.',
    respiratoryDisease: 'Avoid outdoor activities. Take prescribed medications.',
    cardiovascularDisease: 'Avoid outdoor activities. May need medical consultation.',
    suggestions: [
      'Wear N95 masks for outdoor activities',
      'Reduce outdoor time, especially in evenings',
      'Use air purifiers at home',
      'Drink plenty of water',
      'Avoid strenuous exercises outdoors',
    ],
  },
  POOR: {
    aqiRange: '201-300',
    generalPopulation: 'Avoid prolonged outdoor activities.',
    children: 'Keep indoors. Minimize outdoor exposure.',
    elderly: 'Must stay indoors. Do not go outside.',
    respiratoryDisease: 'Strictly avoid outdoors. Consult doctor immediately.',
    cardiovascularDisease: 'Strictly avoid outdoors. Consult doctor immediately.',
    suggestions: [
      'Wear N95/N99 masks if you must go outside',
      'Stay indoors with doors and windows closed',
      'Use high-efficiency air purifiers',
      'Reduce physical activity',
      'Seek medical attention if experiencing symptoms',
    ],
  },
  VERY_POOR: {
    aqiRange: '301-400',
    generalPopulation: 'Avoid all outdoor activities.',
    children: 'Must stay indoors at all times.',
    elderly: 'Must remain indoors. Emergency care if needed.',
    respiratoryDisease: 'Emergency medical care may be required.',
    cardiovascularDisease: 'Emergency medical care may be required.',
    suggestions: [
      'Stay indoors completely',
      'Wear N99 masks if absolute emergency to go outside',
      'Keep air purifiers running 24/7',
      'Seal windows and doors',
      'Minimize physical activity',
      'Seek immediate medical attention for any symptoms',
    ],
  },
  SEVERE: {
    aqiRange: '401-500+',
    generalPopulation: 'Do not go outside. Emergency situation.',
    children: 'Must remain indoors at all times.',
    elderly: 'Must remain indoors. Emergency measures.',
    respiratoryDisease: 'Emergency medical care required immediately.',
    cardiovascularDisease: 'Emergency medical care required immediately.',
    suggestions: [
      'Do not go outside under any circumstances',
      'Keep windows and doors sealed',
      'Use heavy-duty air purifiers',
      'Call emergency services for any breathing difficulties',
      'Wear P100 masks only if absolutely necessary to go outside',
      'Consider evacuation if available',
    ],
  },
};
